[package]
name = "simple_summation"
version = "0.1.0"
authors = ["David Ross <daboross@daboross.net>"]

[dependencies]
wasm-wrapper-gen = { version = "0.0.1", path = "../../" }

[build-dependencies]
wasm-wrapper-gen-build = { version = "0.0.1", path = "../../wasm-wrapper-gen-build" }
